import type { Metadata } from "next";
import { GrainOverlay } from "@/components/grain-overlay";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://api.fontshare.com/v2/css?f[]=satoshi@1,2&f[]=comico@400&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <GrainOverlay />
        <main>{children}</main>
      </body>
    </html>
  );
}
